language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '10'
  - '12'
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
services:
  - postgresql
script:
  - npm run test
